version: "3.9"
services:
  krbclient:
    build: ./client-krb
    container_name: docker_krbclient_1
    networks:
      - "example"
    domainname: "example.com"
    volumes:
      - "./..:/spark-connector"
      - "./client-krb:/client-krb"
      - "./vertica-hdfs-config/hadoop-kerberized:/etc/hadoop/conf"
    stdin_open: true
    env_file:
      - "krb.env"
    ports:
      - "5005:5005"
  kdc:
    build: ./kdc
    container_name: "kdc"
    networks:
      - "example"
    hostname: "kdc"
    domainname: "example.com"
    env_file:
      - "krb.env"
    volumes:
      - "./kdc:/kdc"
      - "./keytabs:/keytabs"
    privileged: true
  vertica:
    image: "vertica/vertica-k8s:${VERTICA_VERSION:-latest}"
    container_name: "vertica"
    networks:
      - "example"
    hostname: "vertica"
    domainname: "example.com"
    entrypoint: ["/bin/bash", "-c", "/opt/vertica/bin/docker-entrypoint.sh"]
    ports:
      - "5433:5433"
    volumes:
      - "./vertica-krb:/vertica-krb"
      - "./keytabs:/keytabs"
      - "./vertica-hdfs-config/hadoop-kerberized:/etc/hadoop/conf"
    env_file:
      - "krb.env"
    privileged: true
  hdfs:
    build: ./hdfs-krb
    container_name: "hdfs"
    networks:
      - "example"
    hostname: "hdfs"
    domainname: "example.com"
    ports:
      - "22022:22"
      - "8020:8020"
      - "50010:50010"
      - "50020:50020"
      - "50070:50070"
      - "50071:50071"
      - "50075:50075"
      - "50076:50076"
    stdin_open: true
    tty: true
    volumes:
      - "./vertica-hdfs-config/hadoop-kerberized:/hadoop/conf"
      - "./hdfs-krb:/hdfs-krb"
      - "./keytabs:/keytabs"
    env_file:
      - "krb.env"
    privileged: true
    entrypoint: /bin/bash
  minio:
    image: minio/minio
    container_name: minio
    networks:
      - example
    hostname: minio
    domainname: example.com
    entrypoint: sh
    command: -c 'mkdir -p /data/test && minio server /data --console-address ":9001"'
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
volumes:
  minio-data:
networks:
  example:
    name: "EXAMPLE.COM"
    driver: bridge
