name: Move labeled issue
on:
  issues:
    types:
      - labeled
  workflow_dispatch:
jobs:
  move-low-priority:
    if: github.event.label.name == 'Low Priority'
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: Backlog
          column: Low Priority
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  move-normal-priority:
    if: github.event.label.name == 'Normal Priority'
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: Backlog
          column: Normal Priority
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  move-high-priority:
    if: github.event.label.name == 'High Priority'
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: Backlog
          column: High Priority
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
