name: Run Functional Tests

on:
  workflow_call:
    inputs:
      spark-version:
        required: true
        type: string
      vertica-version:
        required: true
        type: string
  workflow_dispatch:

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    env:
      VERTICA_VERSION: 11.1.1-2
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2
      - name: Run docker compose
        run: cd docker && docker-compose up -d
      - name: Create db in Vertica
        run: docker exec docker_vertica_1 /bin/sh -c "opt/vertica/bin/admintools -t create_db --database=docker --password='' --hosts=localhost"
      - name: Replace HDFS core-site config with our own
        run: docker exec docker_hdfs_1 cp /hadoop/conf/core-site.xml /opt/hadoop/etc/hadoop/core-site.xml
      - name: Replace HDFS hdfs-site config with our own
        run: docker exec docker_hdfs_1 cp /hadoop/conf/hdfs-site.xml /opt/hadoop/etc/hadoop/hdfs-site.xml
      - name: Copy partitioned parquet data to HDFS container
        run: docker cp ./functional-tests/src/main/resources/3.1.1 docker_hdfs_1:/partitioned
      - name: Copy partitioned parquet data to hadoop from local
        uses: nick-invision/retry@v2
        with:
          timeout_seconds: 20
          max_attempts: 10
          retry_on: error
          command: docker exec docker_hdfs_1 hadoop fs -copyFromLocal /partitioned /3.1.1
      - name: Download the build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-jar-file
          path: ./functional-tests/lib/
      - name: Increase active sessions in database
        uses: nick-invision/retry@v2
        with:
          timeout_seconds: 20
          max_attempts: 10
          retry_on: error
          command: docker exec docker_vertica_1 vsql -c "ALTER DATABASE docker SET MaxClientSessions=100;"
      - name: Copy functional tests to home directory of client container
        run: docker exec docker_client_1 cp -r /spark-connector/functional-tests /home
      - name: Copy version.properties file from client container
        run: docker exec docker_client_1 cp -r /spark-connector/version.properties /home
      - name: Run the integration tests on Spark 3.0
        run: docker exec -w /home/functional-tests docker_client_1 sbt run -DsparkVersion="3.3.0" -DhadoopVersion="3.3.0"
      - name: Remove docker containers
        run: cd docker && docker-compose down