name: Nightly Compilation Testing
# Compiles our connector nightly and only report on failure.
# This allows us to stay on top of breaking change from Spark
on:
  schedule:
    # Nightly at 9:18 GMT
    - cron: '18 9 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2
      - name: Build the project
        run: cd connector && sbt package
      - name: Upload the build artifact
        uses: actions/upload-artifact@v1
        with:
          name: build-jar-file
          path: /home/runner/work/spark-connector/spark-connector/connector/target/scala-2.12/spark-vertica-connector_2.12-3.2.0.jar
  slack-workflow-status:
    name: Post Workflow Status To Slack
    needs:
      [
        run-integration-tests-vertica-10-1-1-0,
      ]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        if: always()
        with:
          # Required Input
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_CHANNEL_WEBHOOK}}
          # Optional Input
          name: 'Nightly Spark Connector Compilation'
          icon_emoji: ':ezy:'
