name: Remove Closed Issue
on:
  issues:
    types:
      - closed
  workflow_dispatch:
jobs:
  remove-low-priority:
    if: contains(github.event.issue.labels.*.name, 'Low Priority')
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Backlog
          column: Low Priority
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          action: delete

  remove-normal-priority:
    if: contains(github.event.issue.labels.*.name, 'Normal Priority')
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Backlog
          column: Normal Priority
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          action: delete

  remove-high-priority:
    if: contains(github.event.issue.labels.*.name, 'High Priority')
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Backlog
          column: High Priority
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          action: delete
